version: '3.8'
services:
  redis:
    image: redis:alpine
    restart: always
    networks:
      - walcel-network

  file-server:
    build:
      context: ./walcel-be
      dockerfile: Dockerfile.filesrv
    ports:
      - "${FILE_SERVER_PORT:-5100}:5100"
    volumes:
      - sqlite-db:/usr/src/app/database
      - ./storage:/usr/src/app/storage
    env_file:
      - walcel-be/.env
    depends_on:
      redis:
        condition: service_started
    restart: always
    networks:
      - walcel-network

  deploy-service:
    build:
      context: ./walcel-be
      dockerfile: Dockerfile.deploysrv
    ports:
      - "${DEPLOY_SERVICE_PORT:-5200}:5200"
    volumes:
      - sqlite-db:/usr/src/app/database
    env_file:
      - walcel-be/.env
    depends_on:
      redis:
        condition: service_started
    restart: always
    networks:
      - walcel-network

  frontend:
    build:
      context: ./walcel-fe
      dockerfile: Dockerfile
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    depends_on:
      deploy-service:
        condition: service_started
      file-server:
        condition: service_started
      pinning-service:
        condition: service_started
    restart: always
    networks:
      - walcel-network

networks:
  walcel-network:

volumes:
  ipfs_data:
  ipfs_export:
  sqlite-db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./storage/sqlite-db
